version: 2.1

commands:
  early_return_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is useful to avoid steps that will fail due to missing credentials.
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Nothing to upload for forked PRs, so marking this step successful"
              circleci step halt
            fi

jobs:
  test:
    docker:
      - image: node:current-alpine
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run tsc-check

  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - early_return_for_forked_pull_requests
      - setup_remote_docker
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN
      - run: docker build -f docker/Dockerfile -t logquacious .
      - run: docker tag logquacious squareup/logquacious:latest
      - run: docker tag logquacious squareup/logquacious:$CIRCLE_SHA1
      - run: docker push squareup/logquacious:latest
      - run: docker push squareup/logquacious:$CIRCLE_SHA1

workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
